# sops configuration for Alessandro Saglia CV
creation_rules:
  # Apply these rules to all files ending with .enc.yaml
  - path_regex: .*\.enc\.yaml$
    age: "age145sfasdv74x64xwl9lf3qpz2j96yg595r4vhhyem6dd9gkeurcpsc78gjr"